apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
    traefik.ingress.kubernetes.io/priority: "1"
spec:
  rules:
    - host: int.herodev.es
      http:
        paths:
          - path: /
            backend:
              serviceName: dashboard
              servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  ports:
    - name: http
      port: 80
  type: ExternalName
  externalName: int.herodev.es.s3-website-eu-west-1.amazonaws.com
