image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/raise-base:latest

stages:
  - prepare
  - build
  - deploy
  - review
  - test
  - deploy-prod
  - test-prod
  - tag
  - publish
  - cleanup

variables:
  AWS_DEFAULT_REGION: eu-west-1
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
  BASTION: 'bastion'
cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - $CI_PROJECT_DIR/packages/testing/.cache/Cypress

# Generic for all pipelines

.build-deps:
  script:
    - yarn --pure-lockfile
    - yarn ci:build:deps

# Includes

include:
  - '/packages/client/.gitlab-ci.yml'
  - '/packages/components/.gitlab-ci.yml'
  # - '/packages/onboarding/.gitlab-ci.yml'
  - '/packages/pages/.gitlab-ci.yml'

# Generic jobs

build-deps-generic:
  stage: prepare
  before_script:
    - apk add --update bash
    - pip install awscli
  after_script:
    - mv ./packages/components/dist components
    - mv ./packages/onboarding/dist onboarding
    - aws s3 rm s3://raise-actirfact-pipeline/components
    - aws s3 cp --recursive components  s3://raise-actirfact-pipeline/components
    - aws s3 rm s3://raise-actirfact-pipeline/onboarding
    - aws s3 cp --recursive onboarding  s3://raise-actirfact-pipeline/onboarding
  extends:
    - .build-deps
  only:
    refs:
      - merge_requests
      - master
    changes:
      - 'packages/components/**/*'
      - 'packages/onboarding/**/*'
  except:
    variables:
      - $BUTTERCMS
  artifacts:
    name: DEPS-GEN
    paths:
      - packages/components/dist
      - packages/onboarding/dist
lint:
  stage: build
  script:
    - 'yarn --pure-lockfile'
    - 'yarn lint'
  only:
    - merge_requests
  except:
    refs:
      - master
    variables:
      - $BUTTERCMS

tag to latest:
  image: alpine:latest
  stage: tag
  before_script:
    - |
      #!/bin/sh
      apk add --update openssh-client bash git
      eval $(ssh-agent -s)
      echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts
  script:
    - git remote set-url origin git@gitlab.com:raisehq/${CI_PROJECT_NAME}.git
    - git tag latest --force
    - git push --force origin --tags
  only:
    - master
  except:
    variables:
      - $BUTTERCMS
  resource_group: production
