image: node:11-alpine

before_script:
  - |
    #!/bin/sh
    apk add --no-cache --virtual .build-deps \
    ca-certificates \
    make \
    g++ \
    wget \
    git \
    python \
    py-pip \
    tar && \
    cd /usr/local/bin && \
    wget https://yarnpkg.com/latest.tar.gz && \
    tar zvxf latest.tar.gz && \
    ln -s /usr/local/bin/dist/bin/yarn.js /usr/local/bin/yarn.js && \
    cd - \
    apk del .build-deps

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME: test.herodev.es
cache:
  key: '${CI_COMMIT_REF_SLUG}'

build:
  stage: build
  variables:
    REACT_APP_COOKIE_DOMAIN: .${BUCKET_NAME}.${DOMAIN}
    REACT_APP_HOST_URL: https://${BUCKET_NAME}.${DOMAIN}
  script:
    - |
      echo $REACT_APP_HOST_URL
      yarn --pure-lockfile
      yarn run client:build:integration
  artifacts:
    when: always
    paths:
      - packages/client/build

deploy:
  image: 'python:3.7-alpine'
  stage: deploy
  before_script:
    - 'pip install awscli'
  script:
    - |
      mv packages/client/build latest
      echo ${BUCKET_NAME}
      aws s3 --recursive mv s3://${BUCKET_NAME}/latest s3://${BUCKET_NAME}/old
      aws s3 sync --delete latest s3://${BUCKET_NAME}/latest
