stages:
  - build
  - deploy
  - test

variables:
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
  BASTION: 'bastion'
cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - $CI_PROJECT_DIR/packages/testing/.cache/Cypress

build-front-integration:
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/raise
  stage: build
  script:
    - 'echo $REACT_APP_HOST_URL'
    - 'yarn --pure-lockfile'
    - 'yarn run client:build:integration'
    - 'mv  packages/client/build  packages/client/build_int'
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - packages/client/build_int

deploy-int:
  image: python:3.7-alpine
  stage: deploy
  before_script:
    - 'pip install awscli'
  script:
    - |
      #!/bin/sh
      mv packages/client/build_int build_int
      aws s3 sync --delete build_int s3://${BUCKET_NAME_INT}/ --metadata-directive REPLACE --cache-control max-age=86400000,public
      aws s3 cp s3://${BUCKET_NAME_INT}/ s3://${BUCKET_NAME_INT}/ --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control max-age=0,must-revalidate,public
      for dist in $(aws cloudfront list-distributions --output=text --query 'DistributionList.Items[*].[Id, DefaultCacheBehavior.TargetOriginId'] | grep "$BUCKET_NAME_INT" | cut -f1); do
        echo $dist
        aws cloudfront create-invalidation --distribution-id $dist --paths "/*";
      done
  only:
    - merge_requests

cypress-e2e-production:
  image: 'cypress/browsers:node10.16.0-chrome77'
  stage: test
  variables:
    CYPRESS_url: 'https://app.herodev.es'
    CYPRESS_baseUrl: 'https://app.herodev.es'
    CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
    CYPRESS_api: https://api.herodev.es
    CYPRESS_isCanary: 'false'
  before_script:
    - echo "Rewrite before script"
  script:
    - 'yarn --pure-lockfile'
    - 'cd packages/testing'
    - 'yarn run cypress cache path'
    - 'yarn run cypress cache list'
    - 'yarn run cypress verify'
    - 'yarn run ci:run'
  artifacts:
    expire_in: '1 week'
    when: always
    paths:
      - packages/testing/cypress/screenshots
      - packages/testing/ganache_db
      - packages/testing/cypress/videos
      - packages/testing/cypress/snapshots
  cache:
    key: ganache-global-cache
    paths:
      - packages/testing/ganache_db
  only:
    - merge_requests
