image: node:11-alpine

before_script:
  - |
    #!/bin/sh
    apk add --no-cache --virtual .build-deps \
    ca-certificates \
    make \
    g++ \
    wget \
    git \
    python \
    py-pip \
    tar && \
    cd /usr/local/bin && \
    wget https://yarnpkg.com/latest.tar.gz && \
    tar zvxf latest.tar.gz && \
    ln -s /usr/local/bin/dist/bin/yarn.js /usr/local/bin/yarn.js && \
    cd - \
    apk del .build-deps

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME: test.herodev.es
cache:
  key: '${CI_COMMIT_REF_SLUG}'

build:
  stage: build
  variables:
    REACT_APP_COOKIE_DOMAIN: .${BUCKET_NAME}
    REACT_APP_HOST_URL: https://${BUCKET_NAME}
  script:
    - |
      echo $REACT_APP_HOST_URL
      yarn --pure-lockfile
      yarn run client:build:integration
  artifacts:
    when: always
    paths:
      - packages/client/build

deploy canary:
  image: 'python:3.7-alpine'
  stage: deploy
  before_script:
    - 'pip install awscli'
  script:
    - |
      mv packages/client/build canary
      echo ${BUCKET_NAME}
      aws s3 sync --delete canary s3://${BUCKET_NAME}/canary
  dependencies:
    - build

e2e:
  image: 'cypress/browsers:node10.16.0-chrome77'
  stage: test
  variables:
    CYPRESS_url: 'https://${BUCKET_NAME}/canary'
    CYPRESS_baseUrl: 'https://${BUCKET_NAME}/canary'
    CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
    CYPRESS_api: https://api.herodev.es
  before_script:
  - |
    #!/bin/sh
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    netcat \
    git-all \
    libudev-dev \
    libusb-1.0-0-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
  script:
    - 'yarn --pure-lockfile'
    - 'cd packages/testing'
    - 'yarn run cypress cache path'
    - 'yarn run cypress cache list'
    - 'yarn run cypress verify'
    - 'yarn run ci:run'
  artifacts:
    expire_in: '1 week'
    when: always
    paths:
      - packages/testing/cypress/screenshots
      - packages/testing/ganache_db
      - packages/testing/cypress/videos
      - packages/testing/cypress/snapshots
  cache:
    key: ganache-global-cache
    paths:
      - packages/testing/ganache_db
  dependencies:
    - deploy canary

deploy latest:
  image: 'python:3.7-alpine'
  stage: deploy
  before_script:
    - 'pip install awscli'
  script:
    - |
      mv packages/client/build latest
      echo ${BUCKET_NAME}
      aws s3 sync --delete latest s3://${BUCKET_NAME}/latest
  dependencies:
    - e2e
