image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/raise-base:latest

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-west-1
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
  BASTION: 'bastion'
cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - $CI_PROJECT_DIR/packages/testing/.cache/Cypress

build-components:
  stage: build
  script:
    - yarn
    - cd packages/components
    - npm run build:umd
  artifacts:
    when: always
    paths:
      - packages/components/dist

build-onboarding:
  stage: build
  script:
    - yarn install --frozen-lockfile --stream  --scope '{@raisehq/onboarding,@raisehq/libs}'
    - cd packages/onboarding  & yarn build
    - yarn rollup
  artifacts:
    when: always
    paths:
      - packages/libs/build

deploy-components:
  image: python:3.7-alpine
  stage: deploy
  variables:
    LIB_BUCKET_NAME: lib.raise.it
  before_script:
    - 'pip install awscli'
  script:
    - |
      #!/bin/sh
      mv packages/components/dist components
      ls -la components
      aws s3 cp components/raisecomponents.umd.development.js s3://${LIB_BUCKET_NAME}/components/ --metadata-directive REPLACE --cache-control max-age=86400000,public
      aws s3 cp components/raisecomponents.umd.development.js.map s3://${LIB_BUCKET_NAME}/components/ --metadata-directive REPLACE --cache-control max-age=86400000,public
      aws s3 cp components/raisecomponents.umd.production.js s3://${LIB_BUCKET_NAME}/components/ --metadata-directive REPLACE --cache-control max-age=86400000,public
      aws s3 cp components/raisecomponents.umd.production.js.map s3://${LIB_BUCKET_NAME}/components/ --metadata-directive REPLACE --cache-control max-age=86400000,public

deploy-onboarding:
  image: python:3.7-alpine
  stage: deploy
  variables:
    LIB_BUCKET_NAME: lib.raise.it
  before_script:
    - 'pip install awscli'
  script:
    - |
      #!/bin/sh
      mv packages/libs/build onboarding
      aws s3 sync --delete onboarding s3://${LIB_BUCKET_NAME}/onboarding/ --metadata-directive REPLACE --cache-control max-age=86400000
