image: node:11
stages:
  - prepare
  - build
  - deploy
  - test
  - review
  - cleanup

variables:
  AWS_DEFAULT_REGION: eu-west-1 
  npm_config_cache: "$CI_PROJECT_DIR/packages/testing/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/packages/testing/.cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
    - packages/client/node_modules
    - packages/components/node_modules
    - packages/onboarding/node_modules
    - packages/testing/contracts
    - "$CI_PROJECT_DIR/packages/testing/.cache/Cypress"

lerna:
  stage: prepare
  script:
    - npx lerna bootstrap
    - npx lerna run compile:components
    - npx lerna bootstrap
    - npx lerna run compile:onboarding
    - npx lerna bootstrap
    - cd packages/testing/ && npm i
  only:
    - merge_requests
    - master

build-front-review:
  stage: build
  script:
    - npm run client:build:integration
  only:
    - merge_requests
  except:
    - master
  artifacts:
    when: always
    paths:
      - packages/client/build

build-front-production:
  stage: build
  script:
    - npm run client:build:production
  only:
    - master
  artifacts:
    when: always
    paths:
      - packages/client/build

deploy-review:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - mv packages/client/build $(echo ${CI_BUILD_REF_NAME} | tr A-Z a-z)
    - aws s3 rm s3://${BUCKET_NAME}/$(echo ${CI_BUILD_REF_NAME} | tr A-Z a-z)/ --recursive
    - aws s3 sync $(echo ${CI_BUILD_REF_NAME} | tr A-Z a-z) s3://${BUCKET_NAME}/$(echo ${CI_BUILD_REF_NAME} | tr A-Z a-z)
  only:
    - merge_requests
  except:
    - master

deploy-prod:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - mv packages/client/build build
    - aws s3 rm s3://${BUCKET_NAME_INT}/ --recursive
    - aws s3 rm s3://${BUCKET_NAME_PROD}/ --recursive
    
    - aws s3 sync build s3://${BUCKET_NAME_INT}/
    - aws s3 sync build s3://${BUCKET_NAME_PROD}/
  only:
    - master

# two jobs that run after "install" job finishes
# NPM dependencies and Cypress binary should be already installed
cypress-e2e:
  image: cypress/base:10
  stage: test
  variables:
    CYPRESS_url: http://${CI_BUILD_REF_NAME}.review.$DOMAIN
    CYPRESS_baseUrl: http://${CI_BUILD_REF_NAME}.review.$DOMAIN
    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/packages/testing/.cache/Cypress"
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y netcat && apt-get install git-all -y && apt-get install libudev-dev libusb-1.0-0-dev -y && apt-get clean && rm -rf /var/lib/apt/lists/*
  script:
    - cd packages/testing
    - npm i
    # show where the Cypress test runner binaries are cached
    - $(npm bin)/cypress cache path
    # show all installed versions of Cypress binary
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify
    - npm run ci:run
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - packages/testing/cypress/screenshots
      - packages/testing/cypress/videos
      - packages/testing/cypress/snapshots
  only:
    - merge_requests
    - master

# cypress-e2e-chrome:
#   image: cypress/browsers:chrome67
#   stage: test
#   variables:
#     CYPRESS_url: http://${CI_BUILD_REF_NAME}.review.$DOMAIN
#     CYPRESS_baseUrl: http://${CI_BUILD_REF_NAME}.review.$DOMAIN
#     CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/packages/testing/.cache/Cypress"
#   before_script:
#     - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y netcat && apt-get install git-all -y && apt-get install libudev-dev libusb-1.0-0-dev -y && apt-get clean && rm -rf /var/lib/apt/lists/*
#   script:
#     - cd packages/testing
#     - npm i
#     # show where the Cypress test runner binaries are cached
#     - $(npm bin)/cypress cache path
#     # show all installed versions of Cypress binary
#     - $(npm bin)/cypress cache list
#     - $(npm bin)/cypress verify
#     - npm run ci:run
#   artifacts:
#     expire_in: 1 week
#     when: always
#     paths:
#       - packages/testing/cypress/screenshots
#       - packages/testing/cypress/videos
#       - packages/testing/cypress/snapshots
#   only:
#     - merge_requests
#     - master

review:
  stage: review
  script:
    - echo "Review Launch"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://${CI_BUILD_REF_NAME}.review.$DOMAIN
    on_stop: stop-review
  only:
    - merge_requests
  except:
    - master

stop-review:
  image: "python:latest"
  stage: cleanup
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/$(echo ${CI_BUILD_REF_NAME} | tr A-Z a-z) --recursive
  when: manual
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  only:
    - merge_requests
  except:
    - master
