image: node:11-alpine

before_script:
  - |
    #!/bin/sh
    apk add --no-cache --virtual .build-deps \
    ca-certificates \
    make \
    g++ \
    wget \
    git \
    python \
    py-pip \
    tar && \
    cd /usr/local/bin && \
    wget https://yarnpkg.com/latest.tar.gz && \
    tar zvxf latest.tar.gz && \
    ln -s /usr/local/bin/dist/bin/yarn.js /usr/local/bin/yarn.js && \
    cd - \
    apk del .build-deps

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME: test.herodev.es
cache:
  key: '${CI_COMMIT_REF_SLUG}'

build:
  stage: build
  script:
    - 'echo $REACT_APP_HOST_URL'
    - 'yarn --pure-lockfile'
    - 'yarn run client:build:production'
  artifacts:
    when: always
    paths:
      - packages/client/build

deploy:
  image: 'python:3.7-alpine'
  stage: deploy
  variables:
    BUILD: build_${CI_COMMIT_SHORT_SHA}
  before_script:
    - 'pip install awscli'
  script:
    - |
      mv packages/client/build ${BUILD}
      aws s3 sync --delete ${BUILD} s3://${BUCKET_NAME}/${BUILD} --metadata-directive REPLACE --cache-control max-age=86400000,public
      aws s3 cp s3://${BUCKET_NAME}/${BUILD} s3://${BUCKET_NAME}/${BUILD} --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control max-age=0,must-revalidate,public
      for dist in $(aws cloudfront list-distributions --output=text --query 'DistributionList.Items[*].[Id, DefaultCacheBehavior.TargetOriginId'] | grep "$BUCKET_NAME" | cut -f1); do
        echo $dist
        aws cloudfront create-invalidation --distribution-id $dist --paths "/*";
      done
