stages:
  - test

variables:
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
cache:
  paths:
    - $CI_PROJECT_DIR/packages/testing/.cache/Cypress

cypress-private-image:
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/cypress:latest
  stage: test
  variables:
    CYPRESS_url: 'https://app.herodev.es'
    CYPRESS_baseUrl: 'https://app.herodev.es'
    CYPRESS_CACHE_FOLDER: ${CI_PROJECT_DIR}/packages/testing/.cache/Cypress
    CYPRESS_api: https://api.herodev.es
    CYPRESS_isCanary: 'false'
  script:
    - yarn run ci:run
  artifacts:
    expire_in: '1 week'
    when: always
    paths:
      - packages/testing/screenshots
      - packages/testing/ganache_db
      - packages/testing/videos
      - packages/testing/snapshots
  cache:
    key: ganache-global-cache
    paths:
      - packages/testing/ganache_db
  only:
    - merge_requests

