image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/raise-base:latest

stages:
  - prepare
  - build
  - deploy
  - review
  - test
  - deploy-prod
  - test-prod
  - tag
  - publish
  - cleanup

variables:
  AWS_DEFAULT_REGION: eu-west-1
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
  BASTION: 'bastion'
cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - $CI_PROJECT_DIR/packages/testing/.cache/Cypress

# Generic for all pipelines

.build-deps:
  script:
    - NODE_ENV=production yarn --pure-lockfile
    - cd /packages/components
    - yarn build:bili
    - cd ../../
    - cd /packages/onboarding
    - yarn build:bili
    - cd ../../

# Includes

include:
  - '/packages/client/.gitlab-ci.yml'
  - '/packages/components/.gitlab-ci.yml'
  - '/packages/onboarding/.gitlab-ci.yml'
  - '/packages/pages/.gitlab-ci.yml'

# Generic jobs

build-deps-generic:
  image: node:14.4.0-alpine3.10
  stage: prepare
  before_script:
    - apk update
    - apk add --no-cache --virtual .build-deps python3-dev build-base wget git
  extends:
    - .build-deps
  only:
    refs:
      - merge_requests
      - master
    changes:
      - 'packages/pages/**/*'
      - 'packages/client/**/*'
  except:
    variables:
      - $BUTTERCMS
  artifacts:
    when: always
    paths:
      - packages/components/dist
      - packages/onboarding/dist

# lint:
#   stage: build
#   script:
#     - 'yarn --pure-lockfile'
#     - yarn run client:build:integration:bili
#     - 'yarn run lint'
#   only:
#     - merge_requests
#     - latest
#   except:
#     refs:
#       - master
#     variables:
#       - $BUTTERCMS
#   artifacts:
#     when: always
#     paths:
#       - packages/client/build_review

tag to latest:
  image: alpine:latest
  stage: tag
  before_script:
    - |
      #!/bin/sh
      apk add --update openssh-client bash git
      eval $(ssh-agent -s)
      echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts
  script:
    - git remote set-url origin git@gitlab.com:raisehq/${CI_PROJECT_NAME}.git
    - git tag latest --force
    - git push --force origin --tags
  only:
    - master
  except:
    variables:
      - $BUTTERCMS
  resource_group: production
