image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/raise-base:latest

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-west-1
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/packages/testing/.cache/Cypress
  BASTION: 'bastion'
cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - $CI_PROJECT_DIR/packages/testing/.cache/Cypress

build-components:
  stage: build
  script:
    - yarn install --frozen-lockfile --stream --scope '@raisehq/components'
  artifacts:
    when: always
    paths:
      - packages/components/build

build-onboarding:
  stage: build
  script:
    - yarn install --frozen-lockfile --stream  --scope '{@raisehq/onboarding,@raisehq/libs}'
    - cd /packages/onboarding  & yarn build
    - yarn rollup
  artifacts:
    when: always
    paths:
      - packages/onboarding/dist

deploy-components:
  image: python:3.7-alpine
  stage: deploy
  variables:
    LIB_BUCKET_NAME: lib.raise.it
  before_script:
    - 'pip install awscli'
  script:
    - |
      #!/bin/sh
      packages/components/build components
      aws s3 sync --delete components/cards/raisecomponents.umd.production.min.js s3://${LIB_BUCKET_NAME}/components/ --metadata-directive REPLACE --cache-control max-age=86400000,public
      aws s3 sync --delete components/loan-charts/raisecomponents.umd.development.min.js s3://${LIB_BUCKET_NAME}/components/ --metadata-directive REPLACE --cache-control max-age=86400000,public
      aws s3 sync --delete components/loan-charts/raisecomponents.umd.production.2.min.js s3://${LIB_BUCKET_NAME}/components/ --metadata-directive REPLACE --cache-control max-age=86400000,public

deploy-onboarding:
  image: python:3.7-alpine
  stage: deploy
  variables:
    LIB_BUCKET_NAME: lib.raise.it
  before_script:
    - 'pip install awscli'
  script:
    - |
      #!/bin/sh
      packages/onboarding/build onboarding
      aws s3 sync --delete onboarding s3://${LIB_BUCKET_NAME}/onboarding/* --metadata-directive REPLACE --cache-control max-age=86400000
