build-pages-review:
  stage: build
  variables:
    REACT_APP_COOKIE_DOMAIN: .${CI_COMMIT_REF_SLUG}.www-review.$DOMAIN
    REACT_APP_HOST_URL: https://${CI_COMMIT_REF_SLUG}.www-review.$DOMAIN
    PUBLIC_URL: https://${CI_COMMIT_REF_SLUG}.www-review.$DOMAIN
  script:
    - |
      #!/bin/sh
      if [ -n "${REVIEW_SLUG}" ]; then
        REACT_APP_COOKIE_DOMAIN=.${REVIEW_SLUG}.www-review.$DOMAIN
        REACT_APP_HOST_URL=https://${REVIEW_SLUG}.review.${DOMAIN}
        PUBLIC_URL=https://${REVIEW_SLUG}.www-review.$DOMAIN
      fi
      echo ${REACT_APP_HOST_URL}
      yarn --pure-lockfile
      yarn run pages:build:integration:bili
      mv  packages/pages/public  packages/pages/build_review
  only:
    - merge_requests
    - latest
  except:
    refs:
      - master
    variables:
      - $BUTTERCMS
  artifacts:
    when: always
    paths:
      - packages/pages/build_review

build-pages-integration:
  stage: build
  script:
    - 'echo $REACT_APP_HOST_URL'
    - 'yarn --pure-lockfile'
    - 'yarn run pages:build:integration'
    - 'mv  packages/pages/public  packages/pages/build_int'
  only:
    refs:
      - master
  except:
    variables:
      - $BUTTERCMS
  artifacts:
    when: always
    paths:
      - packages/pages/build_int

build-pages-production:
  stage: build
  script:
    - 'echo $REACT_APP_HOST_URL'
    - 'yarn --pure-lockfile'
    - 'yarn run pages:build:production'
    - 'mv  packages/pages/public  packages/pages/build'
  only:
    refs:
      - master
    variables:
      - $BUTTERCMS
  artifacts:
    when: always
    paths:
      - packages/pages/build

deploy-int-pages:
  image: python:3.7-alpine
  stage: deploy
  before_script:
    - apk add --update bash
    - pip install awscli
  script:
    - |
      #!/bin/sh
      mv packages/pages/build_int build_int
      aws s3 rm s3://${BUCKET_NAME_INT_WWW}/ --recursive
      aws s3 cp build_int s3://${BUCKET_NAME_INT_WWW}/ --recursive --metadata-directive REPLACE --cache-control max-age=86400000,public
      ./cache_invalidation.sh herodev.es
  only:
    - master
  except:
    variables:
      - $BUTTERCMS

deploy-prod-pages:
  image: python:3.7-alpine
  stage: deploy-prod
  before_script:
    - apk add --update bash
    - pip install awscli
  script:
    - |
      #!/bin/sh
      mv packages/pages/build latest
      aws s3 rm s3://${BUCKET_NAME_PROD_WWW}/ --recursive
      aws s3 cp latest s3://${BUCKET_NAME_PROD_WWW}/ --recursive --metadata-directive REPLACE --cache-control max-age=86400000,public
      ./cache_invalidation.sh raise.it
  only:
    refs:
      - master
    variables:
      - $BUTTERCMS
  resource_group: production

review-landing:
  image: python:3.7-alpine
  stage: review
  before_script:
    - apk add --update bash
    - pip install awscli
  script:
    - |
      #!/bin/sh
      if [ -n "${REVIEW_SLUG}" ]; then
        CI_COMMIT_REF_SLUG=${REVIEW_SLUG}
      fi
      echo ${CI_COMMIT_REF_SLUG}
      rm -r -f $(echo ${CI_COMMIT_REF_SLUG} | tr A-Z a-z)
      mv packages/pages/build_review $(echo ${CI_COMMIT_REF_SLUG} | tr A-Z a-z)
      aws s3 sync --delete $(echo ${CI_COMMIT_REF_SLUG} | tr A-Z a-z) s3://${BUCKET_NAME_REVIEW_WWW}/$(echo ${CI_COMMIT_REF_SLUG} | tr A-Z a-z)

  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: 'http://${CI_COMMIT_REF_SLUG}.www-review.$DOMAIN'
    on_stop: stop-review-landing
  only:
    - merge_requests
    - latest
  except:
    - master

stop-review-landing:
  image: python:3.7-alpine
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache openssh-client bash
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$GITLAB_PRIV_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME_REVIEW_APP}/$(echo ${CI_COMMIT_REF_SLUG} | tr A-Z a-z) --recursive
    - aws s3 rm s3://${BUCKET_NAME_REVIEW_WWW}/$(echo ${CI_COMMIT_REF_SLUG} | tr A-Z a-z) --recursive
    - ssh ubuntu@${BASTION}.${DOMAIN} delete_review ${CI_COMMIT_REF_SLUG}
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - merge_requests
  except:
    refs:
      - master
    variables:
      - $BUTTERCMS
